Feat: normalization TCOM
Cour-de-cassation/juritcom pull request #13
Opened 2024-10-14 14:44 UTC by juliengrach-cassation

2024-12-17 14:24 UTC, SebCourvoisier commented
J'aurais besoin d'un regard Data et Label sur `src/batch/normalization/services/computeOccultation.ts` : construction des `categoriesToOmit` et des `additionalTerms`

2024-12-17 15:07 UTC, mauryaland requested changes
2-3 ajustements à faire pour `categoriesToOmit`

2024-12-17 15:07 UTC, mauryaland commented on src/batch/normalization/services/computeOccultation.ts
> +    categoriesToOmit.push(Categories.ETABLISSEMENT)
Voir commentaire plus haut mais la mention **géomorale** ne concerne pas les **établissements** mais les **localités**

2024-12-17 15:07 UTC, mauryaland commented on src/batch/normalization/services/computeOccultation.ts
> +    categoriesToOmit.push(Categories.LOCALITE)
Seulement le **cadastre** ? A vérifier mais je ne vois pas pourquoi on retire **adresse** et **localité** des catégories à occulter

2024-12-17 15:07 UTC, mauryaland commented on src/batch/normalization/services/computeOccultation.ts
> +    categoriesToOmit.push(Categories.PROFESSIONNELAVOCAT)
La catégorie **professionnel avocat** n'est normalement jamais occulté

2024-12-17 16:49 UTC, SebCourvoisier commented
Merci je vais regarder tout ça. Cette gymnastique qui consiste à passer d'une liste de ce qu'on veut occulter à une liste de ce qu'on ne veut pas occulter me fait vriller le cerveau à chaque fois...

2024-12-17 17:10 UTC, mauryaland commented on src/batch/normalization/services/computeOccultation.ts
> +    categoriesToOmit.push(Categories.PROFESSIONNELAVOCAT)
Ok je vois !

2024-12-19 15:35 UTC, ajeanneney commented on src/batch/normalization/services/computeOccultation.ts
> +    categoriesToOmit.push(Categories.PROFESSIONNELAVOCAT)
J'arrive après la bataille sur ce sujet mais voila ce que je peux ajouter : 
avoir ou non la catégorie PROFESSIONNELAVOCAT dans categoriesToOmit ne change rien a la pseudo, la catégorie est considérée comme 'alwaysVisible' dans label donc sera toujours envoyée au moteur pour être identifiée mais ne sera jamais pseudonymisée.

2025-01-09 10:50 UTC, merged